### ISSUE TITLE
Extra long time-stretch for super slow motion video?

### ISSUE THREAD

**Issue by cblc** [dbry/audio-stretch#13]
Looking at the [commit](https://github.com/dbry/audio-stretch/commit/a3a64371525592bb9b5f7b0b72c9433e3e3eef4c) in which you extended the stretch range from [0.5, 2.0] to [0.25, 4.0], I'm understanding that the limits don't come from just what's considered reasonable quality, but that the implementation depends on those limits, and changing them requires a reworking of the source code.

Am I right, or the current implementation could allow for extending the stretch for longer than 4x without changing the source?

My interest, as said in the title, would be for videos in super slow motion. Agreed, at longer than 4x, the audio you can expect is going to be quite weird, but I'd like to have it. Or maybe do you recommend another time-stretch code/algorithm for doing that?

I have no interest in stretching below 0.25x, because I'm talking about slow motion only. So, it's the 4x limit the only one I'd like to remove.

**Comment by dbry** [comment]
The basic algorithm (tdhs) only allows for a 2X stretch maximum. The change I made allows two instances of the algorithm to be cascaded to get to 4X. In other words, the first instance does a 2X stretch, and then we simply route the resulting audio to another independent instance to get to 4X.

The change you reference only allows for the creation of two instances, so there's no way to get more from the existing code without more changes. **However, it would be trivial to create two instances outside the library and pipe the output of one into the next.** Doing this would give you 16X stretch, and it could be extended indefinitely. Of course, like you suggest, it would sound very weird (to me it sounds like the audio is being piped through a hose).

Alternatively there are algorithms more suited for such extreme stretching (although they might not do well with small stretches, which this algorithm works well with). For example there is one called PaulStretch which is open-source and widely available.

Good luck!

**Comment by cblc** [comment]
Ok, thank you very much for clarifying it! Yes, running in several passes should be straightforward to do. I'm closing the issue because it's clear.
