### ISSUE TITLE
unittests?

### ISSUE THREAD

**Issue by hayguen** [dbry/audio-stretch#2]
what would be useful unittests?
any simply generatable test signals?

**Comment by dbry** [comment]
I think including some samples is a good idea. I have a few that I have created in the past, and I also just created an artificial test file to trigger the overflow that you discovered. Assuming GitHub allows (they're big) I will create a folder for them and include them.

**Comment by hayguen** [comment]
@dbry : in case the files are really big, a separate "audio-stretch-data" repository might be appropriate

**Comment by dbry** [comment]
@hayguen I only made the samples big so that I could also use them for performance testing. I think I can easily make short versions for all other testing.

**Comment by hayguen** [comment]
@dbry : then, i'd suggest short files .. and amending a loop count option as command line argument.

**Comment by hayguen** [comment]
Probably a special benchmark option, which does discard the output samples without saving to file ..
and preloads the input file completely into memory, before repeated processing.

**Comment by hayguen** [comment]
it's not a unittest .. but meanwhile having the build and test scripts as well as the audio sample files.
