### ISSUE TITLE
extend range for ratio to 0.25 .. 4.0

### ISSUE THREAD

**Issue by hayguen** [dbry/audio-stretch#5]
direct support for ratio up to 4.0 would be great - correspondig to speed x 0.25,
this is the range, which is offered by many players.

**Comment by dbry** [comment]
The quality of this algorithm at 4X is pretty bad, and 0.25X speech is too fast to understand, but I suppose both of these could be useful in some applications.

Again, like the independent stereo channels, these can easily be implemented on the client side by creating two instances of the stretching code. But it may be something that could be handled in the library also. I think it would involve adding a flag to the initialization call for "dual instance", and then cascading the stretching code internally with each segment getting the square root of the ratio. I'll take a look at how complex this would be.

**Comment by hayguen** [comment]
@dbry : not sure, but I'd think that, if implementation is possible with single instance - with only one single period search .. i'd think it's lower latency and wouldn't need more CPU?

**Comment by dbry** [comment]
@hayguen I think it would be possible to stretch longer than 2.0x with a single instance using just repetition, but I can't imagine how shorter than 0.5x would work without calculating another period.

In any event, I have prototyped a version with cascaded instances. It only uses the increased resources when needed for extended ratios, and it doesn't add very much code. Let me know what you think.

**Comment by hayguen** [comment]
@dbry : just reading your lines. stretching longer imho is more important - probably to check details or pronounciation.
shorter periods than factor 0.5 are useful, but i wouldn't expect good quality: fast skipping of noise should be the application.. until something like voice is heard .. then rewind and replay a bit slower, that understanding is possible. thus, mainly for the new issue "different ratios" ..
i'll have a look into your patch ..

**Comment by hayguen** [comment]
@dbry : have a look at pull request https://github.com/dbry/audio-stretch/pull/10
afterwards, it should be possible to create the 2nd instance `cnxt->next` once, but not using it when ratio is in 0.5 .. 2.0

**Comment by dbry** [comment]
@hayguen Sorry, I should have mentioned that the cascade code was in a very early stage. I have now incorporated your idea for querying the maximum output (I had thought of this too) and added the max ratio to the parameters. I also incorporated your stretch_reset() fix (thanks!). As you say, now you can have dual instance but the "next" one does nothing if the ratio is shallow (not sure if this is exactly what you had in mind). I have downloaded your scripts and will try them out, thanks!

After a little more testing/refinement of this I will experiment with having different ratios for silence detection.

**Comment by hayguen** [comment]
@dbry  implemented and merged into master.
thank you for your great work!
